#!/bin/sh
set -e

lb config noauto \
    --architectures amd64 \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --iso-application "NyxOS" \
    --iso-volume "NYXOS" \
    --iso-publisher "NyxOS Project" \
    --bootappend-live "boot=live components username=nyxos hostname=nyxos" \
    --debian-installer none \
    --apt-recommends true \
    "${@}"
